name: tiktok_double_tap_like
description: A Flutter package that provides a widget for a TikTok-like double-tap-to-like feature, with customizable animation, icon color, and size.

version: 1.0.0
homepage: https://github.com/RensithUdara/tiktok_tap_heart_animation_package
repository: https://github.com/RensithUdara/tiktok_tap_heart_animation_package

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"


dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  tiktok_tap_heart_animation: ^1.0.0
